### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AmooryGit** [Tardo/OdooTerminal#82]
TypeError: Object.hasOwn is not a function
    at chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/page_script.js:161:20
    at chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/page_script.js:183:3
![Screenshot from 2022-10-23 11-58-52](https://user-images.githubusercontent.com/82140789/197383549-75eb54ea-62f7-41c3-96d9-6e0d597eef8c.png)

Issue Appearance when updateted ...

**Comment by Tardo** [comment]
Maybe outdated browser? https://caniuse.com/mdn-javascript_builtins_object_hasown
